[build]
builder = "nixpacks"
buildCommand = "cd .. && npm install && npm run build && cd backend && npm install && npm run build && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy || echo 'migrate falhou - seguindo'; npm start"
restartPolicyType = "on_failure"
